import { Press_Start_2P } from 'next/font/google';

import 'modern-normalize/modern-normalize.css';
import './globals.css';

import type { Metadata } from 'next';
import type { FC, PropsWithChildren } from 'react';

export const press2pButton = Press_Start_2P({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout: FC<PropsWithChildren> = ({ children }) => {
  return (
    <html lang="en">
      <body className={press2pButton.className}>{children}</body>
    </html>
  );
};

export default RootLayout;
